#!/usr/bin/with-contenv bash


[[ -f /config/nginx/nginx.conf ]] && \
    sed -Ei "s/worker_processes ([0-9]+)/worker_processes auto/" /config/nginx/nginx.conf


for fpm_dir in /etc/php*/php-fpm.d/
do
    if [[ ! -f "$fpm_dir/z-fpm-processes.conf" ]]
    then
        cp /defaults/fpm-processes.conf "$fpm_dir/z-fpm-processes.conf"
    fi
done
